export ZSH="$HOME/.oh-my-zsh"

#ZSH_THEME="nanotech"
#ZSH_THEME="emotty"
ZSH_THEME="trapd00r-catppuccin"

plugins=(git)

source $ZSH/oh-my-zsh.sh

source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.plugin.zsh
source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.plugin.zsh

eval "$(zoxide init zsh)"

alias diff='diff --color=auto'
alias grep='grep --color=auto'
alias ip='ip -color=auto'
export LESS='-R --use-color -Dd+r$Du+b$'
alias ping='prettyping'

alias sudo="sudo "
alias uwuf="clear; uwufetch"
alias ff="clear; fastfetch"
alias nv="nvim -u $HOME/.config/nvim/init.vim"
alias hx="helix"
alias ls="lsd"

alias ga="git add"
alias gc="git commit -m"
alias gp="git push origin"
alias gb="git branch"
alias gpull="git pull origin"
alias gcherry="git cherry-pick -x"
alias gtui="gitui -t $HOME/.config/gitui/catppuccin-mocha.ron"
alias gmain="if ! git checkout --track origin/main; then; git checkout main; fi"
function gclone() { git clone "$1" && cd "$(basename $1 .git)" }
function gcco() {
    local message="$1"
    shift

    for coauthor in "$@"; do
        local coauthors="$coauthors
Co-authored-by: $coauthor <${coauthor}@users.noreply.github.com>"
    done

    git commit -m "$message" -m "$coauthors"
}
function gupdate-branch { git fetch "$1" main && git merge "$1"/main }

alias db="distrobox"
alias cp="cp -i"

alias system-upgrade="yes | paru; sudo pacman -Scc --noconfirm; paru -Scc --noconfirm"
alias vencord-upgrade='sh -c "$(curl -sS https://raw.githubusercontent.com/Vendicated/VencordInstaller/main/install.sh)"'

alias clipin="xsel --input --clipboard"
alias clipout="xsel --output --clipboard"

alias shred="shred -uvz"
function shreddir() { find "$1" -type f -exec shred -uvz {} \; rm -rf "$1" }

ff #; tmux ls

export GPG_TTY=$(tty)
gpgconf --launch gpg-agent

function command_not_found_handler() {
    echo -e "Command \e[91m$1\e[0m not found! \e[91mSTUPID! BONK!\e[0m OwO" >&2
    return 127
}

function cd() {
    z "$@" 2>/dev/null || echo -e "Directory \e[91m$*\e[0m not found! \e[91mSTUPID! BONK!\e[0m OwO"
}
